# This is the config to use for regular ctd csv, bottle csv, and nutrient csv merges (all csvs)

# Machine Readable File information - this is used to make the QAQC (AKA the Quagmire)
machine_readable_info:
  machine_readable_files: 
    - /Users/zalmanek/Development/OME-EcoFOCI/EcoFOCI/data/1_SampleCollection/2021_SikuliaqDBO_CruiseData/2021_SikuliaqDBO_CruiseData/MachineReadable_CruiseSampleMetadata_SKQ21-12S.csv
  station_col: 'Cast' 

ctd_data:
  ctd_csv: /Users/zalmanek/Development/OME-EcoFOCI/EcoFOCI/data/1_SampleCollection/2021_SikuliaqDBO_CruiseData/2021_SikuliaqDBO_CruiseData/CTD_skq202115s_final_merged_e10b_3356_5064.csv
  header_row: 0
  unit_row:
  pressure_col_name: pressure
  cast_num_col_name: profile_id
  cast_val_str_to_remove: 
    - 'skq202115sc' # A common string to remove in the cast_num_col_name values to be able to get just the integer. Can have multiple
  group_by_cols_to_average: # Use if there are duplicates for cast/pressure combo (CTD will be merged with Bottle on these columns), and find average across numeric columns
    - profile_id
    - pressure
    - 'time (UTC)'

bottle_data:
  bottle_csv: /Users/zalmanek/Development/OME-EcoFOCI/EcoFOCI/data/1_SampleCollection/2021_SikuliaqDBO_CruiseData/2021_SikuliaqDBO_CruiseData/CTD_raw_BottleFile_SKQ21-12S.csv
  header_row: 0
  unit_row: 1
  pressure_col_name: pressure
  cast_num_col_name: profile_id
  bottle_num_col_name: bottle
  cast_val_str_to_remove:  # A common string to remove in the cast_num_col_name values to be able to get just the integer. CAn have multiple
   - 'SKQ202115Sc'
   - '_btl'
  group_by_cols_to_average: 

nutrient_data:
  nutrient_csv: /Users/zalmanek/Development/OME-EcoFOCI/EcoFOCI/data/1_SampleCollection/2021_SikuliaqDBO_CruiseData/2021_SikuliaqDBO_CruiseData/33BI20211108_SKQ202115S_nutrient_data.csv
  header_row: 22
  unit_row: 23
  pressure_col_name: CTDPRES
  cast_num_col_name: Cast_number
  cast_val_str_to_remove:
  group_by_cols_to_average: